### ISSUE TITLE
Must the version tags include a v?

### ISSUE THREAD

**Issue by dustin** [semver/semver.org#1]
> When tagging releases in a version control system, the tag for a version MUST be "vX.Y.Z" e.g. "v3.1.0".

I've always tagged my versions as `X.Y.Z`, e.g. `3.1.0`.  I pull that directly out with `git describe` for my apps to report their own versions.

**Comment by mojombo** [comment]
I like having the v prepended so that version tags are clearly delineated from other stuff that might happen to start with a number. I guess it just disambiguates a little more than the straight version number by itself.

**Comment by dustin** [comment]
Could it perhaps be changed to a SHOULD with a detail of why you prefer it your way?

For three digit numbers as you have them, it seems unlikely to conflict with anything else (short of someone creating a branch with the same name as the version -- though this doesn't seem to prevent that confusion).

**Comment by mojombo** [comment]
I've moved the tagging requirement into a sub-spec so you can safely ignore it and still be compliant with the main spec.

**Comment by steshaw** [comment]
@mojombo wondering if that sub-spec is public somewheres?

**Comment by mojombo** [comment]
You can see what it looked like in the 1.0.0 spec, though it was removed in later releases:

http://semver.org/spec/v1.0.0.html#tagging-specification-semvertag

**Comment by cschlote** [comment]
As we currently start a discussion on this issue at work, I'd like to add this link: https://github.com/semver/semver.org/issues/50

So the reason why the SemVerTag was removed from the SemVer spec is, that it is out of scope how tags are setup for the different version control systems.

And: Each developer team can use any kind of tag scheme for their version control system, e.g. "v1.2.3" or "release-1.2.3" or "v1.2.3-foo" as long as the embedded SemVer tuple conforms to the SemVer spec.

Using the bare SemVer Tuple is just an easy to parse and also the most simple option. But using a prefix like 'v' can help to "just disambiguates (it) a little more than the straight version number by itself."

For some years now I use the scheme 'v1.2.3' for my projects in Git. For most other revision systems this should work, too. It allows filtering the output of 'git tag' with grep to just geht a list of release tags, while ignoring all other tags for other purposes. Filtering the bare SemVer number requires more effort and more complex regex expressions.
