### ISSUE TITLE
Pre-release designations?

### ISSUE THREAD

**Issue by mikeal** [semver/semver.org#10]
I'm wondering how this system will handle pre-release designations.

In Python + setuptools (a flawed system to be sure) there are a ton of pre-release designations with different weights. pre, rc, beta, b, alpha, a, all of which can also take a version, so the ordering is something like:

1.0
1.0rc2
1.0rc1
1.0b3
1.0a4
1.0alpha2

This is, admittedly, too much, but I do think it's usefull to be able to release a package that is intended to be a pre-release version of a particular semver.

Something like appending pre1, pre2 to the end of a semver would be enough so that leading up to a 1.0 release people could be releasing 1.0pre1 1.0pre2, which is simple enough to parse.

This does complicate some of the ordering and dependency version rules but it's problematic for people who want to release betas to have to either do lots of 0.9.99991 designations.

**Comment by mojombo** [comment]
A number of people have expressed this same concern. I've added a point to the spec that does exactly as you suggest (only in stricter terms). I think this is a fine way to denote special versions while staying out of the way of people that don't need such functionality.
