### ISSUE TITLE
It seems that i'm the author of original idea

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [semver/semver.org#108]
https://www.haskell.org/pipermail/haskell/2006-November/018762.html

**Comment by bronson** [comment]
So what's the issue?  What needs to happen to close it?

**Comment by NewAlexandria** [comment]
Was this a matter of 'independent invention' or @Bulat-Ziganshin were you in discussion with those that put out this idea as "Semantic Versioning."

Perhaps in the 'About' section we just put a line like "Other early examples of the concept can be seen [here](https://mail.haskell.org/pipermail/haskell/2006-November/018762.html), here, and here."

**Comment by haacked** [comment]
The specification says this directly:

>  These rules are based on but not necessarily limited to pre-existing widespread common practices in use in both closed and open-source software.

The pre-existing practices this refers to are so widespread I don't think we could refer to every early example of the concept. I think what the spec says here is sufficient. Feel free to re-open if you disagree.
