### ISSUE TITLE
Programmatically Find Loaded Version

### ISSUE THREAD

**Issue by dstrelau** [semver/semver.org#11]
This may or may not be related to semver, but I figure I'll throw it out there:

It would be great to define a common way to access the current version of the library you are using in a given language. For example, a common pattern in Ruby is:

```
module MyLib
  module Version
    MAJOR = 1
    MINOR = 5
    TINY = 3
    STRING = [MAJOR,MINOR,TINY].join('.')
  end
end
```

Unfortunately, not all libraries follow this. I'd like to see a recommended way to specify the current version in a variety of languages.

**Comment by mojombo** [comment]
I think that's a cool idea, but outside the scope of the SemVer spec. It's going to be VERY hard to get people to agree on how to do this. My current preferred method for Ruby is:

```
module MyLib
  VERSION = "1.5.3"
end
```
