### ISSUE TITLE
How to behave if a project uses SemVer, but its maintainer is made to show the version of that project in SemVer incompatible format?

### ISSUE THREAD

**Issue by dvorapa** [semver/semver.org#115]
Please extend FAQ with this question:

```
FAQ

What to do if any package/app management service requires the 4th number to be filled in?
Just give them zeros and hope they change their opinion one day and let the choice on their users.
```

For more please see https://github.com/mojombo/semver/issues/168

**Comment by haacked** [comment]
Any changes to the FAQ belonge in mojombo/semver. Once they're made in the official spec, they'll show up here when we release that version of the spec.
