### ISSUE TITLE
Add SEMVER text file to spec

### ISSUE THREAD

**Issue by chadwalters** [semver/semver.org#12]
The addition of the SemVerTag subspec is useful for tools that interact with projects in VCS; however, it doesn't provide for tool chains that work over distributed packages. I'd suggest the addition of another subspec that adds a SEMVER text file to the distributed form of software packages. This file could contain the URL to the version of the semver spec that this version of the package is using. You could extend this further, adding a URL to a webservice for the project which could support some kind of REST API that would allow for querying about updates, bad releases, etc.

**Comment by mojombo** [comment]
Yikes. All this seems very heavyweight. I'd like for SemVer to stay extremely simple. Maybe you can draw up a sample subspec, and we could see how it feels first?
