### ISSUE TITLE
Explain why the v is necessary

### ISSUE THREAD

**Issue by schwern** [semver/semver.org#13]
The spec does not explain why vX.Y.Z is better than X.Y.Z.  It seems right but I can't come up with a solid rationale.

**Comment by kristjan** [comment]
I assume you're talking about the tagging specification.

X.Y.Z could be a whole host of things. A date, for instance, where X=mm, Y=dd, Z=yy. Including the 'v' makes it quite clear that this is a version number (or, less likely, a vermin count: mice.mites.moles).

**Comment by schwern** [comment]
Yes, apologies for not being specific.  I'm talking about SemVerTag rule 1.

Confusion over an X.Y.Z tag doesn't seem terribly compelling, but less ambiguity can't hurt.  Anyhow, mostly I'm reporting this issue because I've seen more than my share of X.Y.Z vs vX.Y.Z arguments with little actual content and was hoping the SemVer spec would provide some.  I guess part of the point of a spec is to simply pick one of two nearly equal choices.

**Comment by lsolesen** [comment]
My vote is for just X.Y.Z. It is just as clear as 'vX.Y.Z' in my opinion.

**Comment by schwern** [comment]
As a point of information, Perl requires the v, but this is to disambiguate X.Y.  For historical reasons, X.Y is a decimal version number and is compared as a decimal number.  vX.Y is a dotted integer.  For example, 1.23 means something different from v1.23.

semvar, consistently using X.Y.Z, doesn't have this issue.

**Comment by mojombo** [comment]
The "v" is a namespace to prevent confusion with other tags. I find it useful and it's already quite commonplace.
