### ISSUE TITLE
technical solution proposal

### ISSUE THREAD

**Issue by flazz** [semver/semver.org#14]
conventionally locate a YAML file the _project root_ named **.semver**.

this file loads a Mapping with the appropriate values defined for the following keys:
- major
- minor
- patch
- special

i implemented this for ruby at [flazz/semver](http://github.com/flazz/semver). it is available via gemcutter.

**Comment by mojombo** [comment]
This oversteps the boundaries of what I'm trying to accomplish with SemVer. Additional requirements like this would only serve to polarize potential adopters, as many library maintainers would refuse to clutter up their repos with additional metadata files. It's possible that if some convention arises to perform this task that it can be added to the spec, but I'd like to see it to arise as a successful grass-roots cause first.
