### ISSUE TITLE
Translations order

### ISSUE THREAD

**Issue by modzelewski** [semver/semver.org#146]
It would be nice to have the translation links presented in some order.
Right now translation links are sorted in order they were added. I'm not sure if there is a standard way of sorting languages, but sorting by country code [sounds reasonable](http://ux.stackexchange.com/questions/17064/how-do-you-sort-a-list-of-languages).
Jekyll/Liquid supports sorting collections, so this could be done in the layout file. I'd happy to make the PR if you like this idea. Thanks.

**Comment by haacked** [comment]
I wonder if it's sorted by the order in _config.yaml. We could manually sort it there, but I think having the computer (Jekyll/Liquid) sort it makes it less error prone. I would accept such a PR. Thanks!

**Comment by modzelewski** [comment]
Yep, the order comes from the yaml, so sorting manually would do the job. However having it sorted by the machine makes adding a new translation one step less :)
