### ISSUE TITLE
<html lang="en" dir="ltr">

### ISSUE THREAD

**Issue by magol** [semver/semver.org#154]
# Language

All pages for all languages are notated with "_en_" in the html-tag. 

Please add the language to the [html lang](http://www.w3schools.com/tags/ref_language_codes.asp) attribute
## Example

``` html
<html lang="en" dir="ltr">
<html lang="sv" dir="ltr">
<html lang="es" dir="ltr">
```
# Direction

What about the `dir` attribute? I may be wrong, but is not Arabic written from right to left?

**Comment by haacked** [comment]
Doh! You're correct, this is a bug.

**Comment by magol** [comment]
Great that this is fixed now.
But the language menu has become strange. Where Arabic is chosen, the "Arabic" menu item is cut in half and written both to the left and to the right.  I do not really know what causes this.

One solution is to use `ltr` for the language menu.

This is in Chrome 52
![semver arabic](https://cloud.githubusercontent.com/assets/493140/18946157/f03c3b56-862d-11e6-9251-c21c734e5fc3.PNG)

This is in Internet Explorer 11
![semver arabic - ie](https://cloud.githubusercontent.com/assets/493140/18946277/6c570d7e-862e-11e6-8686-b68dc414a842.PNG)

**Comment by haacked** [comment]
Care to submit a PR for that?

**Comment by haacked** [comment]
@magol I fixed it. Try it out.
