### ISSUE TITLE
Provide example RegEx

### ISSUE THREAD

**Issue by serverhorror** [semver/semver.org#16]
Given that regex is available in all? languages mentioning the best known dialects and corresponding regular expressions to match would be nice:

Python 2.x:

<pre>
^v?(?P<major>\d+)\.(?P<minor>\d+)\.?P<patchlevel>\d+)~?(?P<special>[a-z]\w+[\d+])?$
</pre>

**Comment by serverhorror** [comment]
And now with corrected tags:

<pre>
^v?(?P&lt;major&gt;\d+)\.(?P&lt;minor&gt;\d+)\.?P&lt;patchlevel&gt;\d+)~?(?P&lt;special&gt;[a-z]\w+[\d+])?$
</pre>

**Comment by tbull** [comment]
So I guess Python doesn't use PCRE, does it?
Anyway, here the expressions from my Java implementation (not yet published):

<PRE>
protected static final Pattern special_pattern = 
    Pattern.compile("[A-Za-z][0-9A-Za-z-]*");
protected static final Pattern semver_pattern =
    Pattern.compile("v?(\\d+)(?:\\.(\\d+))?(?:\\.(\\d+))?([A-Za-z][0-9A-Za-z-]*)?");
</PRE>

This expression also accepts version numbers with the minor and/or patch number omitted, e.g. "1.2" or "1alpha".

**Comment by serverhorror** [comment]
I think it does. What you get from my regex is a dictionairy (key/value pairs) where the keys are "major", "minor", "patchlevel", "special" so that you can access the different parts by name and not by index from the regex grouping.

**Comment by JakeWharton** [comment]
@serverhorror your regex doesn't adhere to rule 3 properly. Something like `[a-zA-Z][-a-zA-Z0-9]*` is better for the body of the 'special' clause.

The rule doesn't explicitly declare it, but it seems odd to allow a trailing dash (`-`). Perhaps this should be brought up as another issue. This can be included by changing the 'special' clause to `([a-zA-Z][-a-zA-Z0-9]*)(?<!-)`.

**Comment by mojombo** [comment]
I think this is outside the scope of SemVer. The spec should state the requirements clearly enough to easily construct a RegEx, and if it does not then that is a failure of the spec and should be addressed separately.

**Comment by krainboltgreene** [comment]
I know this is old, but would it be beneficial to have "examples" enough to that implementation builders have test cases?
