### ISSUE TITLE
Need standard for naming libraries which implement protocol versions

### ISSUE THREAD

**Issue by jdunck** [semver/semver.org#17]
There is a common problem in naming libraries when the library itself is versioned, but also implements a version of a protocol.  For example, python's httplib2 (a rethinking of http 1.x support), and the many imaginings of memcache support.

How about some guidance on this naming problem?

<language>-<protocol><protocol version>-<client flavor> ?
So the existing python-oauth2 should be properly named something like:
python-oauth1-simplegeo

**Comment by mojombo** [comment]
I think this is primarily a documentation problem. As a library evolves and changes, documentation should be kept up to date and made clear where the protocol boundaries lie. It's a hard problem to solve with something as simple as version numbers.

**Comment by jdunck** [comment]
I see what you're saying; I wasn't arguing that the semantic should be just within the version number.  Rather that semver is the first sort of general guidance on packaging that I've seen w/ traction, and it seems a fairly natural place to provide more broad guidance.  Not to say what a name should be, but perhaps what it shouldn't be.  :-)

**Comment by mojombo** [comment]
Do you have any concrete ideas on this concept? If you could sketch out some guidelines that made sense, that would be something to at least start a discussion around.

**Comment by jdunck** [comment]
[originating organization]-[language/name]-[protocol], specifically precluding numbers in the name, and requiring a readme explanation of which versions are supported?

e.g. simplegeo-python-oauth
dsallings-python-github
