### ISSUE TITLE
semver seems to be geared at libraries, am i right?

### ISSUE THREAD

**Issue by cies** [semver/semver.org#18]
with the central notion of the "public api" semver effectively limits itself to libs. end user apps, that usually do not need to define a public api, could also benefit from semver. especially packagers, distro maintainers and system administrators could benefit a lot from the semver scheme.

**Comment by cmcknight** [comment]
I disagree. If you create an application that has a public API then you'd be equally bound to properly document and support the application API.

**Comment by rzezeski** [comment]
I also disagree, the idea of API is much more general than the words it stands for.  In the case of a web application, the API is the set of resources (URIs) you provide.  In the case of a desktop application, the API is the GUI that drives the application.  Etc.

API is more general than a set of functions/methods that may be called.

**Comment by cies** [comment]
@cmcknight: you're right. so it limits itself to libs and webservices.

@progski: sorry but you take this too far in my opinion. an api is to programmers not to users. your notion of api misses the "a" and the "p" and just leaves the "i" of interface, in that case gui=api (dismissing the first 2 letters of both).

> API is more general than a set of functions/methods that may be called.

true, sometimes it also describes data structs, classes and protocols. but it _never_ describes buttons, forms, layout, menubars and other gui stuff.

**Comment by cmcknight** [comment]
I'm not sure that I would limit it to libs and "web" services either. An application could take an action based on a file that appears on a file system. The "API" would be a file read and the contents of the file could be in an agreed upon 'protocol'. I would suggest that if I have any externally accessible interfaces, regardless of the way the interface is accessed, then I am responsible for documenting the interface. There are more ways to get data in and out of applications than are dreamt of in your philosophies.  ;-)

**Comment by mojombo** [comment]
If you can figure out a way to pin down something akin to an API, then you can apply the principles of SemVer. Some things are better fits than others. If it's a useful construct, go for it.

**Comment by cies** [comment]
This discussion to some extend continued in this thread:

https://github.com/mojombo/semver/issues/90

I've also send in a pull request with generalizes the semver text to "interfaces" in general. I think it is a very sound generalization and makes server both more useful and the text more precise.

@mojombo please have a look at it, I'm curious what you think of it.
