### ISSUE TITLE
Allow 3 or more numbers

### ISSUE THREAD

**Issue by christianromney** [semver/semver.org#19]
Rather than limit the version number to 3 (major, minor, patch), consider allowing a scheme where the last 3 parts are used for semver and an initial N parts are reserved for vendor-specific semantics. IIRC, .NET Assemblies use 4 parts (major, minor, build, revision). Also, in many development organizations and for many products bumping a major version number implies more than breaking API compatibility. Like it or not, end users associate features with major version numbers especially for commercial, paid software. Nor does a series of iterative evolutions of an API necessarily denote irresponsible development or lack of foresight. It's equally possible to evolve and improve an API over a series of well planned releases containing few, if any new features. 

In any case, for projects that want to use 3 parts, great no change to the spec, but allowing projects that want to retain semantic control over major version numbers the option to do so while simultaneously embracing semver and living up to its promises seems like an easy win.

**Comment by while0pass** [comment]
how about thinking out the specification for semantic versioning API. For instance, a file with a series of variables like API_CHANGE, API_EXTENDING, PATCH, BUILD, REVISION and so on. And system of version tags with different purposes: API dependency versioning, marketing versioning and so on.

**Comment by mojombo** [comment]
SemVer is intended for libraries, not huge conglomerate products without a well-defined public API. Keeping the spec simple is paramount, even if it means not working for a few edges cases or very large systems.

**Comment by christianromney** [comment]
Agreed, but I think this use case stands on its own: 
http://msdn.microsoft.com/en-us/library/51ket42z(v=vs.71).aspx 

I know these projects would benefit. :)

https://github.com/languages/C%23
https://github.com/languages/Visual%20Basic

**Comment by christianromney** [comment]
Perhaps my original wording was unnecessarily broad as well. Rather than N reserved parts, just 1 would cover the .NET use case...

**Comment by christianromney** [comment]
Last bit of additional info: http://blogs.msdn.com/b/jjameson/archive/2009/04/03/best-practices-for-net-assembly-versioning.aspx

**Comment by mojombo** [comment]
I don't think build numbers belong in SemVer. It's easy enough to use the revision from version control for this purpose, duplicating it in a version number intended for public consumption feels messy.
