### ISSUE TITLE
Github should totally pimp semver with an optional repo badge

### ISSUE THREAD

**Issue by jamesbebbington** [semver/semver.org#2]
When creating a new repo it would be nice to have the option of stating that your library adheres to the principles laid out at semver.org which when selected would display a badge in the #repos div and/or perhaps some sort of boilerplate preface to the readme.

**Comment by sjl** [comment]
This could be related to #3 -- if something like that is added to the specification it would be trivial for GitHub to parse it and display such a badge/link/etc.

**Comment by jamesbebbington** [comment]
Ooh, I like your thinking!

**Comment by mojombo** [comment]
We're playing with the idea of different kinds of badges for users and repos. It's possible that we could do something like this on GitHub in the future. I like the idea of surfacing specific features to somewhere easy to notice. I'll think some more about this.

**Comment by mojombo** [comment]
It's unlikely we'll do anything with badges on github.com any time soon, so I'm closing this issue. You never know what the future holds, though.
