### ISSUE TITLE
Encourage namespacing

### ISSUE THREAD

**Issue by nirvdrum** [semver/semver.org#20]
I think the part about bumping the major version if making an incompatible change to the public API should be amended.  A public API should never be changed.  If you want to do so, you should use a different namespace.

The reason for this is most library management system simply won't let you activate two versions of the same library.  So, if awesome-gem 2.0 comes out and it's incompatible with awesome-gem 1.2, it's effectively the same thing as introducing a backwards-incompatible change in the 1.x series.  Your entire dependency chain needs to either be on 1.x or 2.0 and that's oftentimes difficult to achieve (patching N libraries is problematic and it only takes one to spoil the party).

However, if awesome-gem 2.0 uses the Awesome2 namespace or whatever, you can basically include both versions of the library in a single artifact.  Microsoft does this and it works rather well, if not a bit klunky.  The nice part about it is an app declares they adhere to particular interface, not a particular version of the artifact, allowing 2.0 to include 1.2 and letting the dependency chain live coexist happily.

**Comment by koraktor** [comment]
I don't really want to judge about your request, but to be honest I never saw an application rely on two versions of the same dependency. Additionally, most dependency management systems (like RubyGems, Maven etc.) don't even allow something like that. So why should a version naming specification allow (or even enforce) that?

**Comment by nirvdrum** [comment]
Not the app per se, but the dependency chain.  E.g., I use vanity, resque, redis-store, redis-session-store, and a few other things that all use redis-rb.  redis-rb releases a new major version that's not backwards-compatible and as soon as one of these libs requires it, they all must.  There's no way for each lib to stick to its version of the API because RubyGems in this case doesn't allow activation of two different versions of the same lib.  I.e., the 2.0 version effectively pollutes the 1.x version anyway.

**Comment by mojombo** [comment]
I agree that namespaces might be a good solution to the multiple-installs problem, but the matter is tied too closely to specific languages and falls outside the scope of SemVer, which I'm trying to keep as simple and unencumbered as possible.
