### ISSUE TITLE
Relationship between Major/Minor/Patch versions unclear

### ISSUE THREAD

**Issue by tiestvilee** [semver/semver.org#21]
Do you intend for your semver spec to define the relationships between the Major/Minor/Patch numbers?  At the moment rule #2 implies that the individual components increment independently.  For example

1.9.0
1.10.0
2.10.0

With no resetting of the Minor release number.  If you care, then maybe there should be a clause that says that the Patch number resets to 0 when the Minor release number increments, and the Minor number and Patch number reset to 0 when the Major number increments.

**Comment by algonzalez** [comment]
While I think most would infer the resetting as you describe, it would be probably be best to have it stated explicitly in the spec.

**Comment by GraemeF** [comment]
I agree, this needs to be explicit.

**Comment by thecodejunkie** [comment]
Agreed. We've had the same discussion on the project that I run.

**Comment by mojombo** [comment]
This will be more explicit in the SemVer 1.0.0 upcoming release.
