### ISSUE TITLE
No rule about how big an increment version numbers can change

### ISSUE THREAD

**Issue by tiestvilee** [semver/semver.org#22]
Rule #2 says that the version numbers "increase numerically" but this only implies that they increment by 1.  Increasing by 3 is still a numerical increase.  Even the example uses the less than sign rather than some kind of implication or chaining

If you care about the numbers only incrementing by 1 (which really annoys my friend Lauri when people don't do it) then this should be made explicit.

**Comment by mojombo** [comment]
This is covered in the latest spec at mojombo/semver.
