### ISSUE TITLE
updating a dependency could affect the API

### ISSUE THREAD

**Issue by rzezeski** [semver/semver.org#23]
In the FAQ you state that updating a dependency does not affect the public API but I don't think that statement always holds water.  I don't have a concrete example but I could imagine a situation where your code relies on a 3rd party library that produces data that is returned by your API.

E.g., lets say you have an application that takes a string as input, performs some type of transformation on the string, and then returns the resulting string.  Lets also say this transformation is performed by a 3rd party library called "string-thingy-1.0.0."  This means that your API is dependent on the API of  3rd party library.  Imagine if the creators of string-thingy release version 2.0.0, which introduces a change in the result of the transformation function you are using.  If you upgrade to this new version you have now broken your own API.

If your app/lib relies on only semver projects, then you could probably devise some safe rules about upgrading dependencies. If not, then all bets are off.  The library may have broken it's API during a patch level release...the only way to know would be to read the release notes and test.

What do you think?

**Comment by beoran** [comment]
In this case, if you don't want to update your API, you'll have to wrap the the lower level API and ensure the results your API returns stay the same. Wrapping other lower level API's always means you should try to isolate your users from changes in those lowerlevel API's.

**Comment by mojombo** [comment]
I agree with @beoran. The public API is your responsibility as a library maintainer. If you upgrade a dependency, you need to make sure your API is not affected. Automated test suites are great for this kind of verification.

**Comment by rzezeski** [comment]
I agree, my point was that the FAQ makes the assumption that a dependency can't affect your API.  I felt that this isn't true in all cases and it seems we are in agreement.

**Comment by beoran** [comment]
Well, nice to see we're all agreeing. :) 
I think it's best the FAQ should be corrected to state something like what mojombo said.
