### ISSUE TITLE
Website Is Now Black And White

### ISSUE THREAD

**Issue by jeffery-do** [semver/semver.org#230]
Didn't this site use to have a lot more styling?

I've been linking this page in some of my documentation, and noticed that the UI looked very different from what I remember. At first I thought my browser might be broken, or maybe specific files weren't being loaded.

I just wanted to confirm that a lot of the styling was stripped? Because I feel like the readability, and the confidence in the credibility of the document has been lowered if the styling is being removed.

It may just seem like eye candy, but in my opinion it's pretty important from a marketing perspective. If I show this document to someone else, I want both the navigation and reading experience to be pleasant.

**Comment by alexandrtovmach** [comment]
Hello @jeffery-do 

Not sure how long time ago you saw another version of this website, but it looks like this around two years

**Comment by alexandrtovmach** [comment]
Closed as non-issue. Feel free to re-open it, if there are still some misunderstanding.
