### ISSUE TITLE
No specification regarding deprecation

### ISSUE THREAD

**Issue by dchelimsky** [semver/semver.org#24]
There is currently no guidance on deprecation in the SemVer spec. Should there be?

If so, I see two paths. Both are consistent with other aspects of SemVer, but one is slightly stricter than the other.
### Strict
- When a method is removed, the major version number MUST be incremented, and there MUST be a minor release of the previous major version that includes a deprecation notice.
- When a deprecation warning is added, the minor version number MUST be incremented.
### Relaxed
- When a method is removed, the major version number MUST be incremented, and there MUST be a patch or minor release of the previous major version that includes a deprecation warning.

NOTE that the implication here is that deprecation warnings are programmatic, not just in the docs.

Thoughts?

**Comment by tomkersten** [comment]
Adding either is an improvement, imo.

I prefer the Strict-form outlined above, as it promotes a justified amount of effort on the part of the package maintainer relative to the alternative amount of effort from all the users of the package.  In other words, if I am creating the patch-file, it seems like releasing a minor version is a small step that would be essentially just as easy for the developer to do, versus putting the burden of looking for patch updates on all the users of said library.

I could be swayed on this, as one could argue that if the package maintainer consistently uses a method that is more cumbersome for the user to maintain, less people will use it...and it will, therefore, sort itself out over time.  However, the "Strict" form seems to be more inline with the overall objective of SemVer.

**Comment by beoran** [comment]
I think the more relaxed way of deprecation is better. Deprecated functionality should slowly be phased out, not removed with warnings coming only one version beforehand, so the users of the API have time to adapt to it.

**Comment by tomkersten** [comment]
The "strict form" outlined above does not seem to outline anything which conflicts with phasing out over several minor release though. Instead, it sets a minor release as a _requirement_ (vs. a patch file being an acceptable alternative).

**Comment by dchelimsky** [comment]
@tomkersten - correct. The strict form ensures that end-users see deprecation warnings in a minor release before an item is removed. It requires no immediate action on the part of the user.

Also, it does not requires the maintainer to remove a deprecated item at the next major release - only that a major release is required when the item is removed.

**Comment by tomkersten** [comment]
Cool. My preference on the strict-form still stands...and I think this is a sound addition to the spec. ;-)

**Comment by beoran** [comment]
@tomkersten, that's actually right, however,  I don't actually see what the benefit is of the second clause: "When a deprecation warning is added, the minor version number MUST be incremented.". Deprecation warnings don't really change the API, IMHO. 

How about this simply making the requirement:
"When a method is removed, the major version number MUST be incremented, and there MUST be at least one minor release of the previous major version that includes a deprecation warning." ?

**Comment by dchelimsky** [comment]
@beoran - agreed it doesn't change the API, but it does change the user's perception of the API. If I'm using a SemVer-compliant gem, I expect 0 distractions when taking a patch release, which is presumably being released because there is a bug that users would want fixed.

I realize it puts more constraint on the maintainer, but I think it makes it easier for users to understand what to expect, which is the whole point of this spec.

**Comment by tomkersten** [comment]
+1 on what @dchelimsky's got goin' on up there ^^^

**Comment by beoran** [comment]
@dchelimsky, Well, if most people agree with that, I'll follow it. I'm hoping that some mention of deprecation will make it into the SemVer spec soon.

**Comment by mojombo** [comment]
I agree, the addition of a deprecation warning warrants a minor release. Bug fixes are for just that, bug fixes. Nothing else. The semantics of a minor release fit a deprecation notice well. As such, I am in favor of the Strict form of this proposal and will add it to the 1.0 release of SemVer, which I hope to do soon.

**Comment by cgriego** [comment]
\+ 0.75

> When a method is removed, the major version number MUST be incremented.

Assuming the method is part of the public API, then this is already covered by semver.

> When a deprecation warning is added, the minor version number MUST be incremented.

Agreed.

>  and there MUST be a minor release of the previous major version that includes a deprecation notice.

Disagreed, this is a harsh requirement to apply, especially considering that semver applies to more than just Ruby. I recommend SHOULD.

**Comment by ghost** [comment]
+1 @cgriego

**Comment by zettabyte** [comment]
+1 for @dchelimsky's _STRICT_

**Comment by gavenkoa** [comment]
+1 for @dchelimsky's STRICT but
+1 @cgriego as disagreed with minor release of the previous major version that includes a deprecation notice

**Comment by mojombo** [comment]
See the above commit for how this has been addressed in the next version of SemVer.

**Comment by dchelimsky** [comment]
That looks great. Thank you.

**Comment by tomkersten** [comment]
Awesome.
