### ISSUE TITLE
SemVer vs. pre-released Ruby gems

### ISSUE THREAD

**Issue by AlekSi** [semver/semver.org#25]
SemVer specifies 1.2.3beta1 format, while RubyGems uses 1.2.3.beta1. :(

**Comment by beoran** [comment]
Perhaps both should be allowed and be equivalent?

**Comment by mojombo** [comment]
SemVer 1.0.0 will be adopting the RubyGems style notation with the dot separator. It's easier to parse both visually and by machine.
