### ISSUE TITLE
special versions as used not actually as in spec

### ISSUE THREAD

**Issue by jrochkind** [semver/semver.org#26]
Spec says:

"A special version number MAY be denoted by appending an arbitrary string immediately following the patch version. The string MUST be comprised of only alphanumerics plus dash [0-9A-Za-z-] and MUST begin with an alpha character [A-Za-z]. Special versions satisfy but have a lower precedence than the associated normal version. Precedence SHOULD be determined by lexicographic ASCII sort order. For instance: 1.0.0beta1 < 1.0.0beta2 < 1.0.0"

I think this means that if a customer has locked to, say, ~> 1.2, and you release a 1.3.0alpha1, that would MEET the dependency, right? 1.3.0alpha1 "satisfies but has lower precedence than" (the not yet existing) 1.3.0, which means it meets ~>1.2.  

But I don't think this is the intention of 1.3.0alpha.  Rather the intention of 1.3.0alpha is to essentially return you to a little breakout psuedo-major-level-0 unstable sequence, sort of.  Or I'm not sure about that actually, maybe that's not right. Your thoughts?   Is it appropriate that 1.3.0alpha meets ~>1.2?   If you release 1.3.0alpha1, is it in fact _correct_ that a dependency manager would auto-update a ~>1.2 project to 1.3.0alpha1? That doesn't seem right. 

From the other side, when is it appropriate to tag something with a  "special version" subdividing a patch level?

**Comment by beoran** [comment]
I agree with this. 1.3.0alpha should only match 1.3.0, and not 1.2.

**Comment by ghost** [comment]
I interpret SemVer this way:

```
1.0.0 < 1.0.1beta1 < 1.0.1beta2 < 1.0.1
```

In other words, `1.0.1beta1` satisfies the dependency for `1.0.1` but not for `1.0.0`. But being an alpha/beta/pre-release/whatev it will be superseded by `1.0.1`.

This is how I think version comparison goes given two versions A and B and comparing `A <=> B`:

```
if (A.major <=> B.major != 0) return A.major <=> B.major
if (A.minor <=> B.minor != 0) return A.minor <=> B.minor
if (A.patch <=> B.patch != 0) return A.patch <=> B.patch
if (A.special == B.special) return 0
if (A.special == "") return 1
if (B.special == "") return -1
return A.special <=> B.special
```

**Comment by gavenkoa** [comment]
@toolbear. Agree with your formula.

**Comment by mojombo** [comment]
@toolbear is correct.

**Comment by gavenkoa** [comment]
I read guides for RPM and DEB packages. They use different comparing schema:

  http://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

Briefly version string split into parts of digits and letters. Digit compared as usual, substring with letters in lexical order. Zero letter less than any string. So 1.0.2 < 1.0.2a < 1.0.2alpha < 1.0.2b < 1.0.2beta. For alpha/beta markers used special sign '~'. So 1.0.2~a < 1.0.2~alpha < 1.0.2~b < 1.0.2~beta < 1.0.2.

This version comparing schema works for a largest projects (Debian/Ubuntu/Red Hot/Susy) and for a long time. Just for the record...
