### ISSUE TITLE
On the front page, "Indonesia" should be "bahasa Indonesia"

### ISSUE THREAD

**Issue by rec** [semver/semver.org#262]
A quibble at the top of https://semver.org/: "Indonesia" is the country, "bahasa Indonesia" the language.

While I'm here, "English" and "Deutsch" should be capitalized.  

I quickly checked most of the other language names written in Roman or Cyrillic letters and I'm fairly sure the capitalization is correct for those (ie, capitalized for Türkçe and lower case for the rest).

----

I would have made a pull request for these, except that I cannot find the language names in any of the four files in this repository...

Thanks for a really useful page!

**Comment by alexandrtovmach** [comment]
Investigated a bit and didn't find any ISO spec with language native names ([endonyms](https://inspire.ec.europa.eu/codelist/NativenessValue/endonym#:~:text=Definition%3A,where%20the%20feature%20is%20situated.)) which we are talking about. Instead, I found this doc from Unicode standard: http://cldr.unicode.org/translation/translation-guide-general/capitalization

>Beginning with CLDR 22, the guidance is that names of items such as **languages**, regions, calendar and collation types
>...
>Regarding the capitalization of months and weekdays, please **apply middle-of-sentence capitalization rules even on stand-alone items**.
In your language, if month and day names are generally lower case in the middle of the sentence, then please apply this same rule (lower case) to both formatting and standalone values.
>...
>However, it is also **important to ensure that there is consistent casing for all of the items in a section**, so before making any changes, be sure to **get agreement among all the translators for your language** — otherwise the capitalization of items in a section may appear random.

**Comment by alexandrtovmach** [comment]
Read more about why it's not standardized here:
https://en.wikipedia.org/wiki/Exonym_and_endonym

In addition, few unofficial resources with autonyms that we can use:
- https://polyglotclub.com/wiki/Language/Multiple-languages/Vocabulary/Language-Autonyms-List
- https://github.com/bbqsrc/iso639-databases/blob/master/iso639-autonyms.tsv

**Comment by rec** [comment]
Reading these documents now... gee, someone did all the work already, how nice.  (Also just discovered Blissymbols from the second document.)

Very instructive.  Thanks!
