### ISSUE TITLE
anchor links do not work

### ISSUE THREAD

**Issue by jkasnicki** [semver/semver.org#263]
To repro follow this link:
https://semver.org/#spec-item-4

This just take you to the top of the page instead of item 4.

If you click the hover link icon next to item 4 (or any item) it scrolls to that item, but if you copy that URL and paste into a new tab, it takes you to the top of the page.

**Comment by alexandrtovmach** [comment]
@jkasnicki Thanks for report. Does this issue still reproducible?

**Comment by jkasnicki** [comment]
Yes, still repros.

I am now on MacOSX 10.14.6 (Mojave).

The link DOES work on:
Firefox (version 76.0.1)

The link does NOT work on:
Chrome (version 83.0.4103.97)
Safari (version 13.1.1 (14609.2.9.1.3))

**Comment by alexandrtovmach** [comment]
@jkasnicki thanks for clarifying, will check
