### ISSUE TITLE
HTML Anchors on semver.org

### ISSUE THREAD

**Issue by thegcat** [semver/semver.org#27]
Having HTML anchors on semver.org would make linking to specific parts of the page easier, those should be at least on the titles, having them on individual points would be nice too.

**Comment by GaryJones** [comment]
+1. What you're after is id attributes on key elements.

**Comment by kelvinst** [comment]
I'd like the idea, maybe I work on it when I get time.

**Comment by ghost** [comment]
:+1:

**Comment by AndersDJohnson** [comment]
+1 Any chance of this? Harder to encourage & enforce the spec when we can't direct link to specific tenets.
