### ISSUE TITLE
Internal API vs External API

### ISSUE THREAD

**Issue by ericbmerritt** [semver/semver.org#29]
Just a little clarity since the discussion has come up in relation to one of my projects.

I would like a clear definition of internal vs external API. Many languages have explicit exports for functions from modules. Those explicit exports are those functions that are designed to be used by other modules. They are the API for that module, and a public API for better or for worse. Now bring in intention, just because those modules export an API does not mean that those modules are intended to be used outside of the library they are a part of. So does a change to the exported API of a module that is not designed to be used outside of the library constitute a change of the Public api and require a minor version change, or is it a patch version change?

The relevant piece of the doc is here ->

Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.

**Comment by mojombo** [comment]
The public API can be whatever you define. That might be the exported functions of a module, or it may be a subset of that. What matters most is that some public API can be identified, generally via documentation of some sort.
