### ISSUE TITLE
Examples with consecutive dashes create Markdown formatting errors

### ISSUE THREAD

**Issue by Nixinova** [semver/semver.org#291]
The example "1.0.0+21AF26D3----117B344092BD" contains a triple hyphen, which Markdown converts to an em-dash, outputting "1.0.0+21AF26D3—-117B344092BD" outside of GitHub. This example should be changed to no longer have concurrent hyphens.

**Comment by Nixinova** [comment]
#320 reports that the same issue is found with an example in spec item 9: `1.0.0-x-y-z.--.` creates `1.0.0-x-y-z.–.`

**Comment by greggirwin** [comment]
I just hit this as well, while working on a semver parser.

**Comment by ardnew** [comment]
Also just found the two instances of defective symbols mentioned above, 
so no need for me to repeat their findings.

But even with these symbols fixed — i.e., replaced with ASCII hyphens "-" —
the wording of spec item 9 is misleading, ambiguous, or at least inconsistent:

> Identifiers MUST comprise only ASCII alphanumerics and hyphens `[0-9A-Za-z-]`.

Would recommend avoiding trying to name the members of that class, 
because the character class expresses it much more concisely and accurately than English,
and it avoids endlessly digging yourself out of ambiguity traps.

> Identifiers MUST be composed entirely of members in the ASCII characters class `[0-9A-Za-z-]`.

**Comment by hmmwhatsthisdo** [comment]
Just encountered this as well, which complicated debugging a SemVer parser issue (the examples I copy/pasted from semver.org weren't parsing with the provided regexes).

This appears to be [by-design](https://kramdown.gettalong.org/syntax.html#typographic-symbols) for Kramdown, the default markdown renderer for Jekyll (which powers gh-pages).

According to the docs (and other [similar issues](https://github.com/docker/docker.github.io/issues/4178)), there are three options:
* Escape the offending dashes in the underlying Markdown source (i.e. `1.0.0+21AF26D3----117B344092BD` becomes `1.0.0+21AF26D3\-\-\-\-117B344092BD`)
  * This would require escaping a lot of dashes within the spec
* Put _all_ example versions in inline code-blocks (i.e. `1.0.0+21AF26D3----117B344092BD` becomes `` `1.0.0+21AF26D3----117B344092BD` ``)
  * This requires more individual changes to the spec than option 1, but is portable across renderers
* Disable typographic symbol conversion using the [`no_auto_typographic` quirk](https://github.com/kramdown/parser-gfm#options) within Kramdown's configuration
  * This has significant side-effects for the rest of the document (namely disabling smart quotes and the like)
* Use a renderer other than Kramdown

I'd suggest Option 2 for several reasons:
* Escaping individual dashes isn't a common requirement when writing Markdown, so future contributors may not realize it's necessary
* Disabling typographic symbol conversion for the whole site (even the page) has broad side-effects
* Using code-blocks for inline examples has other benefits (e.g. different display behavior)

If formatting changes to the spec are too much of a hurdle, then Option 3 is probably the second-best (but would have non-trivial changes across semver.org).

**Comment by JohnTitor** [comment]
https://github.com/semver/semver.org/pull/394 resolved this, closing.
