### ISSUE TITLE
Programatically determining if a project is using semantic versioning.

### ISSUE THREAD

**Issue by sjl** [semver/semver.org#3]
From the website:

> If all of this sounds desirable, all you need to do to start using Semantic Versioning is to declare that you are doing so and then follow the rules. Link to this website from your README so others know the rules and can benefit from them.

This is great because it lowers the barrier to entry to almost nothing, but it has a couple of problems.

What if tools (such as packaging systems) want to take advantage of the wonderful metadata that semantic versioning provides?  The fact that 3.1.0 and 3.1.1 should be interchangeable (and 3.1.1 is better because it has fixed bugs) would be very nice to know when calculating dependencies.

However, this numbering scheme has been used to mean many different things, so a tool couldn't just assume that projects with `vX.Y.Z` tags are using the scheme.

Another issue is with projects that currently use `vX.Y.Z` tags but _don't_ use the same meanings for these tags: how do they _start_ using semantic versioning?  If they say "we are using semantic versioning" then assumptions about meanings of version numbers won't hold true for the earlier parts of their history.

There needs to be a way to say "as of version X.Y.Z we are now using semantic versioning".  Saying that in the README will work for humans but again fails for programmatic use.

The first solution that comes to my mind is pretty simple.  Simply add two requirements to the "what you need to do to start using semantic versioning" section:
1. A project is not considered to be using semantic versioning unless there is at least one tag of the form `vX.Y.Z` somewhere in its history.  This should be pretty obvious.
2. A project is not considered to be using semantic versioning unless there is a `semver` tag that points at a changeset somewhere in its history, and that changeset must _also_ have a `vX.Y.Z` tag pointing to it.

This solves the problems I've mentioned:
- A tool can tell if a project is using SV by checking for a `semver` tag and a `vX.Y.Z` tag pointing at the same changeset.
- A project can declare themselves to be using SV from version X.Y.Z onward by adding a single tag.  Tools can parse this and can know to only apply rules relating to SV to versions later than that.

I don't think this is too much of a barrier to entry.  Creating at least one `vX.Y.Z` tag is already a practical requirement -- the only additional command you'd have to run is `hg tag -r vX.Y.Z semver`.  This seems like a small price to pay to allow programmatic detection of this versioning scheme.

Thoughts?

**Comment by sirlancelot** [comment]
How about using a special character like `§X.Y.Z` on the first version/subsequent versions that uses semantic notation? I see problems in just requiring `vX.Y.Z` to be in the history because some people might be doing that already without regard to its meaning in this context.

**Comment by nome** [comment]
Very good. The clarification that the `semver` tag must point to the same changeset as a `vX.Y.Z` tag is missing from the website.

**Comment by mojombo** [comment]
The biggest problem here is that I don't want to require the use of a versioning system in order to be SemVer compliant.

**Comment by trans** [comment]
Just b/c someone says they are using semver doesn't mean they have done so, and especially to perfection. I think we need to be intellectually honest here and see semver for what it is, a strong set of _guidelines_. It is not something that can be readily tested or verified about a project. So I doubt any tools can really make much use of the fact.

That being said, the proper approach would be a field in the project metadata (e.g. gemspec) like `version_policy` set to `semver`.

**Comment by postmodern** [comment]
From the package manager side of things, I only want to see three-part version numbers (with an optional `build` suffix) all separated by a `.`.

From an automated-tool/SCM point of view, only recognizing tags which begin with a `v` is the easiest route. This allows tools to ignore any other non-semver tags (`0.2`) or date tags (`4.20.2010`).

**Comment by mojombo** [comment]
The bottom line is that if it's too hard to be compliant, then nobody well even bother. The spec is lightweight on purpose, to make sure the philosophy is conveyed. For most projects, absolute compliance is impossible because they will never properly specify a Public API. That is fine. As long as the philosophy of SemVer is being understood, then the spec is accomplishing my goal.

**Comment by mojombo** [comment]
SemVerTag will be removed from the spec, so this is no longer an issue. I don't think automatic detection of SemVer compliant packages was ever viable in the first place.
