### ISSUE TITLE
Consider renaming "patch version"

### ISSUE THREAD

**Issue by mlassau** [semver/semver.org#31]
For many software projects a "patch" is an ad-hoc set of files to quickly fix a specific problem (and has no "version" number, although it may have an unrelated "patch" number)
This is rather different to a "bug-fix release".

I would suggest "maintenance version".

**Comment by AndreiRailean** [comment]
Maybe "micro" is a good word to use:
Major.Minor.Micro

**Comment by ghost** [comment]
I've encountered Major.minor.patch far more often than any other verbiage, both in open source and commercial packages. I never heard of Major.minor.micro until OSGi. Instead of trying to force new terminology, I like that SemVer put semantics behind the terminology people were already using.

**Comment by mojombo** [comment]
Many words have many meanings. It's all about context. In the context of SemVer, "patch" means one thing, as defined. I think this will be clear to most people and won't cause any confusion.
