### ISSUE TITLE
Bug fix or incompatible change?

### ISSUE THREAD

**Issue by ewa** [semver/semver.org#35]
This isn't a complaint - and I don't know what to do about it - but it may be worth thinking about anyway:  Not uncommonly, user code relies on "wrong" behavior in the library, and it therefore broken by bug fixes. Either:
- The old version did not match the spec (API), and the new version does, or
- Both versions match the spec, but the new version is somehow better.

In either case, ideal theoretical user code which relied only on the spec wouldn't be broken by the change, but real code might be.  This situation probably just comes down to good judgment, but maybe the Semantic Versioning standard can offer some guidance.

**Comment by mojombo** [comment]
Addressed in https://github.com/mojombo/semver/commit/92b17d297fbdd649157cac60830e0925c9978d6c
