### ISSUE TITLE
Confusion about SemVerTag.

### ISSUE THREAD

**Issue by postmodern** [semver/semver.org#37]
The Rack developers and I are confused whether it is required to prefix version tags with a `v` (https://github.com/rack/rack/issues/185).

The first part of SemVerTag uses the RFC `SHOULD` keyword, implying that SemVerTag is merely a suggested best practice:

> This sub-specification SHOULD be used if you use a version control system (Git, Mercurial, SVN, etc) to store your code.

However, the first numbered item in SemVerTag uses the `MUST` RFC keyword when discussing the `v` prefix:

> When tagging releases in a version control system, the tag for a version MUST be "vX.Y.Z" e.g. "v3.1.0".

Could you clarify this for us, when following SemVer and using an SCM, is prefixing version tags with a `v` required or optional?

**Comment by mojombo** [comment]
IF you want to be SemVerTag compliant then you MUST prefix version numbers with a 'v'. However, SemVerTag is an optional add-on spec that you can choose to use or not.

**Comment by postmodern** [comment]
Suggestion, please make SemVerTag required if the project is using an SCM.

SemVerTag helps distinguish other numeric tags (such as dates: `4.20.2010`) from version tags.

**Comment by mojombo** [comment]
I think that's too much to demand. That would make a ton of otherwise SemVer compliant projects no longer compliant because of a small rule about tagging. The wording strongly suggests you should use SemVerTag if you have version control, and I think that's enough. Are you worried about detecting version numbers with code?

**Comment by postmodern** [comment]
I have made a [Repository](https://github.com/postmodern/sem_ver_tag#readme) explaining why SemVerTag is a good idea, and made a small list of Projects not following it. Hopefully, over time SemVerTag will become as widely adopted as SemVer.

**Comment by mojombo** [comment]
@postmodern Cool, thanks!
