### ISSUE TITLE
Should we translate BNF?

### ISSUE THREAD

**Issue by LaoshuBaby** [semver/semver.org#374]
I meet with a situation that some languages translate words in BNF to their languages, others remain English.

I have a look of all issue in semver/semver.org and found nothing about this problem.

Should we meet with a community consensus about this? Or let translator of that language make decision themselves?

For example, 11 language's localization contain BNF: bg/de/es/hy/ja/ko/nl/ro/uk/zh-CN/zh-TW

But only es/ko translated it to their language. I've mentioned this in https://github.com/semver/semver.org/pull/334

---

label: `consensus seeking`

**Comment by JohnTitor** [comment]
I mentioned this topic here: https://github.com/semver/semver.org/pull/364#issuecomment-1193099400
So I generally think we shouldn't translate BNF as it's a metasyntax but if it makes much sense to translate in their languages and customs, I guess it's probably worth considering accepting it.

With regards to es/ko, AFAIK we haven't received any report that BNF is translated so it's not a serious issue, I guess.
Anyway, I'm going to ping @DarkGhostHunter (es) and @hatemogi (ko) for awareness, who originally translated BNF into their languages. If you agree to revert the translation about BNF, feel free to let me know or submit a PR :)

**Comment by hatemogi** [comment]
@JohnTitor Thanks for mentioning me to know the issue. I'm afraid that I'm not representing about general Korean customs, but I personally thought the BNF contained meanings for human and the meaning was worth to be translated. 

If you guys agreed on some consensus about making the BNF section consistent not to be translated, I am totally happy with reverting it in English, but I am not submitting a PR on it myself.

Thank you.

**Comment by DarkGhostHunter** [comment]
> BNF contained meanings for human and the meaning was worth to be translated.

I agree to this. Unless the BNF is a raw into to something, like it where code to compile, it would be written verbatim.

**Comment by JohnTitor** [comment]
Alright, it seems y'all find it helpful and I'm fine in that case. If a reader raises an issue, let's discuss it further :)

I'm going to close this as there's no actionable item for now.

**Comment by LaoshuBaby** [comment]
Another idea: why not contain both translated and original text?

like this: https://www.conventionalcommits.org/zh-hans/v1.0.0/

![图片](https://user-images.githubusercontent.com/42690037/181149446-0156bbc8-885e-4f5a-9a3c-031f245aa5d3.png)

**Comment by DarkGhostHunter** [comment]
> Another idea: why not contain both translated and original text?

You can switch back to the original eng version if you want.
