### ISSUE TITLE
BG: "semantic versioning" needs to be translated differently

### ISSUE THREAD

**Issue by d78mdd** [semver/semver.org#377]
Здравейте,
мисля, че е по-правилно "semantic versioning" да се превежда като "семантично версиониране" или "семантично създаване на нови версии" или "създаване на нови версии спрямо семантиката".

Hello,
I think the words "semantic versioning" need to be translated differently in bulgarian.

**Comment by JohnTitor** [comment]
cc @atsonkov who originally translated it

**Comment by atsonkov** [comment]
I was also looking for better way to translate it, as I was lacking the good translation of "versioning" (and did not like how it was handled in the Russian or Ukrainian translations either). I got similar comment from another reviewer with some ideas:

> Според мен, това трябва да е "Семантично задаване на версиите". На английски език е "Semantic Versioning", прилагателно и глагол (а може би по-правилно е причастие, но това така или иначе е глаголна форма), съответно. До колкото проверих няма превод на думата "versioning" на български, която определено е глагол (или причастие), тъй като завършва на "-ing". На руски и украински са използвали глаголи, които са просто взети от английския. Би било глупаво и тук да се направи така. Тогава би звучало като "Семантично версициране", което никак не звучи, според мен.

I see that "версиониране" is starting to gain popularity, so I do not mind switching to it. I will need to see if the text still makes sense after replacing all occurances. and prepare PR.

Thanks for the feedback!

**Comment by atsonkov** [comment]
I think this is now resolved and can be closed (as #379 is merged and the changes are published and visible in the Bulgarian translation).
