### ISSUE TITLE
Can‘t list all spec version when Vietnamese selected

### ISSUE THREAD

**Issue by LaoshuBaby** [semver/semver.org#378]
## Description

When select a language, every version in `spec` folder will shown in this navigation bar, but when Vietnamese selected there aren't anything shown, although `v2.0.0.md` already there:

https://github.com/semver/semver.org/blob/aebb54c298eef3cf9c78285f1dcec20f683aa2dd/lang/vi/spec/v2.0.0.md?plain=1#L1-L11

### **en**

![图片](https://user-images.githubusercontent.com/42690037/181257931-201bdeda-dc30-40f7-b1ab-e6f09acc54a0.png)

### **zh-CN**

![图片](https://user-images.githubusercontent.com/42690037/181257880-f2fbf0e1-b811-48f5-a469-cb9b4d044229.png)

### **vi**

![图片](https://user-images.githubusercontent.com/42690037/181258524-b16c14c4-eab3-4b13-a54d-d121115b5f9f.png)

**Comment by JohnTitor** [comment]
Fixed by https://github.com/semver/semver.org/pull/380
