### ISSUE TITLE
Encourage changelogs

### ISSUE THREAD

**Issue by nirvdrum** [semver/semver.org#38]
Each release should warrant an entry in a changelog.  While semver does help communicate the overall magnitude and to a lesser extent, the contents of a change, any project that pushes out a new release really should communicate what those changes are.  Bug fixes should be noted, with security issues called out.  API changes should be clearly documented.  Deprecated methods should indicate replacements.  Etc.

**Comment by mojombo** [comment]
I agree that changelogs are a very important thing to have, but it feels out of scope for SemVer. I want it to be as easy as possible to be compliant, and every additional bit makes it that much more onerous to consider. I think there's room for other small specs around the space of best practices for open source projects. Maybe you could take a stab at writing up what one might look like and the community can discuss where something like that might fit in.
