### ISSUE TITLE
Create translation reviewers list

### ISSUE THREAD

**Issue by JohnTitor** [semver/semver.org#385]
When receiving a translation PR, we pick up reviewers from past contributions (checking git-blame) but it's troublesome to do that each time and some may not want to receive the review requests.
An ideal solution would be having a translation reviewers list to ping.

**Comment by youhong666** [comment]
CONTRIBUTING.md

**Comment by youhong666** [comment]
#291

**Comment by youhong666** [comment]
#383

**Comment by youhong666** [comment]
#377

**Comment by youhong666** [comment]
#384

**Comment by youhong666** [comment]
@JohnTitor

**Comment by youhong666** [comment]
[Uploading BDSG2022997773-1737809381860353-invoice.pdf…]()

**Comment by youhong666** [comment]
[Uploading analytics_com.vivo.website.txt…]()

**Comment by youhong666** [comment]
![Uploading Screenshot_20221012_184444.jpg…]()

**Comment by JohnTitor** [comment]
We now have https://github.com/semver/semver.org/blob/gh-pages/TRANSLATORS.md, closing.
