### ISSUE TITLE
Lexicographic sort order is wrong

### ISSUE THREAD

**Issue by marcelocantos** [semver/semver.org#39]
The following statements are incorrect: "Precedence SHOULD be determined by lexicographic ASCII sort order. For instance: 1.0.0beta1 < 1.0.0beta2 < 1.0.0."

Firstly, the example is wrong. The lexicographic ordering is 1.0.0 < 1.0.0beta1 < 1.0.0beta2, which is clearly not what was intented.

Secondly, lexicographic ordering ignores the numeric nature of the dot components, thus: 1.10.0 < 1.9.0.

An alternative approach would be to specify a canonicalisation of version numbers that ensures the desired ordering. E.g., split the version number into its constituents after appending ~ to an unadorned 3-component version number, as follows:

```
1.0.0beta1 => [1, 0, 0, "beta", 1]
1.0.0beta2 => [1, 0, 0, "beta", 2]
1.0.0 => [1, 0, 0, "~"]
```

**Comment by dominikh** [comment]
As far as I understand the document, the part you quoted applies to string suffixes, which is what the point introduces; not to the overall version sorting.

1) Special versions satisfy but have a lower precedence than the associated normal version
(Therefore 1.0.0beta1 < 1.0.0)

2) Precedence SHOULD be determined by lexicographic ASCII sort order
(Therefore 1.0.0beta1 < 1.0.0beta2)

1 + 2 => 1.0.0beta1 < 1.0.0beta2 < 1.0.0

And 1.10.0 being smaller than 1.9.0 is not a problem, either, since lexicographic sort order only applies to versions with the same numerical compounds but different appended strings.

**Comment by marcelocantos** [comment]
Good point; I should read more carefully. But it's still dubious, since
beta10 will precede beta2.

**Comment by prust** [comment]
I agree that "1.0.0beta1 < 1.0.0beta10 < 1.0.0beta2" is dubious -- it is a common use-case and isn't what is intended.

An alternative to marcelocantos's solution would be to make the specification tighter: "The string MUST be comprised of only alpha characters plus dash [A-Za-z-], followed optionally by numeric characters, e.g. "1.0.0beta1". The string part would be compared lexicographically and the trailing number would be compared numerically.

**Comment by mojombo** [comment]
The latest SemVer spec is moving to the following pre-release paradigm:

> 1. A pre-release version number MAY be denoted by appending a dash and a
>    qualifying string immediately following the patch version. The qualifying
>    string is comprised of a mandatory identifier and an optional sequence number.
>    If the sequence number is used, it MUST be separated from the identifier by a
>    tilde. Identifiers MUST be comprised of only alphanumerics plus dash
>    [0-9A-Za-z-]. Sequence numbers MUST be comprised of only digits [0-9].
>    Pre-release versions satisfy but have a lower precedence than the associated
>    normal version. Precedence SHOULD be determined by lexicographic ASCII sort
>    order of the identifier followed by numeric sort order of the sequence number.
>    If the sequence number is absent, it MUST be considered to be zero. For
>    example: 1.0.0-alpha < 1.0.0-alpha~1 < 1.0.0-beta~2 < 1.0.0-beta~11 <
>    1.0.0-rc~1 < 1.0.0.
