### ISSUE TITLE
Hints from deb packages versioning: explicit sort ordering and special pre-sort character

### ISSUE THREAD

**Issue by lucab** [semver/semver.org#40]
It looks like some doubts are stil existing relating to lexicographic ordering and sorting of the special part (eg. issue #39).
I'd like to propose some enhancements which are already widely in use elsewhere, namely coming from the debian packages versioning scheme, as documented in http://www.unix.com/man-page/all/5/deb-version/
In particular, SemVer may benefit from defining:
-   simple explicit ordering instead of pure lexicographic
-   using a special pre-sorting character, in particular to denote the special version substring

Quoting from the above manpage, version sorting for debian packages is currently defined as:
 "

```
   First  the initial part of each string consisting entirely of non-digit
   characters is determined.  These two parts (one of which may be  empty)
   are  compared lexically.  If a difference is found it is returned.  The
   lexical comparison is a comparison of ASCII values modified so that all
   the  letters  sort earlier than all the non-letters and so that a tilde
   sorts before anything, even the  end  of  a  part.   For  example,  the
   following  parts are in sorted order: '~~', '~~a', '~', the empty part,
   'a'.
   Then the initial part of the remainder of each  string  which  consists
   entirely  of  digit  characters is determined.  The numerical values of
   these two parts are compared, and any difference found is  returned  as
   the  result  of  the  comparison.   For  these purposes an empty string
   (which can only occur at the end of one or both version  strings  being
   compared) counts as zero.
   These  two  steps (comparing and removing initial non-digit strings and
   initial digit strings) are repeated until a difference is found or both
   strings are exhausted.
```

"

While this may not be good as-is verbatim, I think SemVer may adopt similar  ideas.
This will help SemVer avoiding WTF moment in version comparisons and gaining numbers of already available tools to check version ordering (eg. cmd-line tool, postgres-, perl-, python-, etc- modules).

**Comment by mojombo** [comment]
The latest spec at mojombo/semver is much more explicit about sort order.
