### ISSUE TITLE
Major version 0

### ISSUE THREAD

**Issue by hakanensari** [semver/semver.org#41]
Tom et al,

If major version 0 is an anything-goes playground, is or should there be any logic applied to minor or patch versions in that context?

If there was some strong opinion on this, it would be great to express it on the site.

**Comment by gavenkoa** [comment]
Some people state that major 0 also allow API breaking with increasing minor version.

**Comment by mojombo** [comment]
Added this to the FAQ:

### How should I deal with revisions in the 0.y.z initial development phase?

The simplest thing to do is start your initial development release at 0.1.0
and then increment the minor version for each subsequent release.
