### ISSUE TITLE
Resetting lower-precedence components

### ISSUE THREAD

**Issue by JensAyton** [semver/semver.org#43]
Part 8 and 9 of the spec should explicitly state that lower-precedence components reset to zero when X or Y is incremented.

**Comment by gavenkoa** [comment]
Completely agree. But some project (usually proprietary) use patch number as build number. In this case it always incremented.

**Comment by sr105** [comment]
That doesn't conflict. Rev X.Y.0 where Y has just been incremented is build number 0 of X.Y.

**Comment by mojombo** [comment]
Fixed in https://github.com/mojombo/semver/commit/ec80195ed310aab3ae1f1ce797b7ba88b4246d27
