### ISSUE TITLE
Versioning should distinguish API intent from API compatibility

### ISSUE THREAD

**Issue by jcox** [semver/semver.org#44]
**_major_._minor_._patch_** fails to handle the case where some fuzzily-defined 
high-level API intent is nailed down in a later revision in a manner that 
could be breaking.   

Bumping the **_major_** number isn't quite right because to many people 
working  at a low level, the library/program doesn't even really feel different. 
It actually feels like a **_patch_**  -- and if the marketing department starts
weighing in on things, they'll often force the issue.   To them, version 
numbers are about intended capabilities not strict backward compatibility.

Proposal:   **_intent.major.minor.patch_**
Where:
-  _intent_ -- The version of a perhaps fuzzily-defined set of capabilities intended & marketed
-  _major_ -- The strict backward compatibility version, bumped for even the slightest semantic change/reinterpretation
-  _minor_ -- The backward-compatible change version  (e.g.:  backward-compatible features added)
- _patch_  -- The bug fix version.

Thus:
- 4.0.0.0  is an unreleased version of an absolutely brand-new API intent (4) before any augmentation or QA
- 4.0.0.1  is an unreleased version of API intent 4, with a bugfix that was caught before any API augmentation 
- 4.0.1.0  is an unreleased version of API intent 4, with an augmentation but no bugfixes  yet.
- 4.1.0.0  is the first released version of API intent 4  (prior to release it was release candidate 4.0.x.y).
- 4.1.0.1  is the first bugfix of the released version 4.1.0.0
- 4.1.1.0  is the first backward compatible change to released version 4.1.0.x
- 4.2.0.0  is the first potentially breaking change to API intent 4  (e.g:  the previously published version 4.1.x.y).

Note how separating API intent from strict API compatibility avoids confusion 
over bumping the highest version number when only subtle (but potentially 
compatibility-breaking) refinements in the interpretation of an API spec have
taken place.  

This scheme also helps to prevent a divergence between "engineering"  and "marketing" version numbers 
(c.f.:  JDK 1.6 == Java 6)  -- engineers, release management, and product management often see things 
quite differently.  Keeping all parties well clear of astonishment saves a lot of grief.

Aside:  This still plays nicely with https://github.com/mojombo/semver.org/issues/40 (Debian pre-sort characters)

**Comment by jcox** [comment]
The EBNF of Debian versions goes something like this:

```
 version   :  epoch? digits remainder?               ;
 epoch     :  digits ':'                             ;
 remainder :  (decorator? digits  |  decorator)+     ; 
 digits    :  DIGIT+                                 ;
 decorator :  (TILDE | LETTER | PERIOD | PLUS)+      ;
 DIGIT     :  ('0'..'9')                             ;  
 LETTER    :  ('a'..'z' | 'A'..'Z')                  ;
 PERIOD    :  '.'                                    ; 
 PLUS      :  '+'                                    ; 
 TILDE     :  '~'                                    ;     
```

Where:
- **epoch** is used to correct mistakes in the versioning scheme  (by default, it's  "0:")
- **digits**  are sorted numerically
- **decorator** parts are sorted so that:
  
     **TILDE** sorts before all **LETTER** and empty string
    **LETTER** sorts before all non-letters other than **TILDE**

Therefore:

```
0.0 < 0.5 < 0.10 < 0.99 < 1 < 1.0~rc1 < 1.0 < 1.0+b1 < 1.0+nmu1 < 1.1 < 2.0 
```

Note:  by using **TILDE**  or **PLUS** at the start of a decorator, you can make a release appear before or after a one with a non-decorated version number.  That's quite useful.

What I'm suggesting here is that you combine the semantic versioning with Debian's
sort ordering algorithm & other structures like **epoch** in the spec.  

I also think that the Debian convention of separating upstream version from packaged
revision numbers with a hyphen makes a great deal of sense:

```
 upstream_version [-packaged_revision ]
```

**Comment by jrochkind** [comment]
So you're just moving all the semantic meanings over one less significant component, and saying that the major version has no semantic meaning beyond marketting?

**Comment by bobthecow** [comment]
Like the `10` part of OS X?

**Comment by mojombo** [comment]
Part of me loves the idea of epoch versions, and part of me hates it. If all you have is a major version, then the major version conveys both the backwards incompatibility of the package _and_ the marketing intent of the package. This often prevents people from properly incrementing the major version when they should, for fear of how it looks like it changes the intent. On the other side, adding another number that is purely for marketing to the technical version number feels wrong. The added complexity of another number is troubling.

**Comment by audigex** [comment]
It makes sense to an end user or marketing type - otherwise there can be more of a functionality  difference between 1.1 and 1.2 than between 1.2 and 2.0 - a little counterintuitive to one unfamiliar with the versioning system.

**Comment by krainboltgreene** [comment]
Realistically there's nothing wrong with shoving this in the version metadata:

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

v24.4.4+i10, in this case "i" is for "intent".

**Comment by gvlx** [comment]
I think this just confuses things.

Marketing can have whatever numbering they like, we could just attach it as a part of the build number: "V1-b1772" or "V7-sprint648-b8780".

This versioning schema is meant to be used essentially by machines on automated management and deployment and as a guide for developers.

Any other use is secondary to this matter. Otherwise it won't help nor please anyone.

**Comment by haacked** [comment]
Sorry for the confusion, but this repository is for the semver.org website. Discussions of the spec itself should be held in https://github.com/mojombo/semver
