### ISSUE TITLE
Guidance for handling "version of master"

### ISSUE THREAD

**Issue by glenjamin** [semver/semver.org#45]
Given a project where development is ongoing, and releases happen by setting the version in an application description file and tagging that commit...

If you make a subsequent commit to that project before releasing it - what would you recommend the version number of the HEAD revision be?

ie.

rev 1: hack hack hack
rev 2: version = 0.1.0 (tag v0.1.0)
rev 3: hack hack hack

At revision 3, if someone were to checkout/build the head revision, the project would report itself as v0.1.0, but would actually be a newer version.

**Comment by mojombo** [comment]
I suggest you keep the version number the same on master until you are ready to make a release. That way, if someone wants to pull the latest dev version and install it, it will cleanly install over the latest version without causing conflicts with future releases.
