### ISSUE TITLE
How to make the transition from 2.1.0.116 to SemVerTag

### ISSUE THREAD

**Issue by Ro42** [semver/semver.org#48]
Currently i am at my own version 2.1.0.116
Now i want to introduce SemVersioning.
Ok, i have to set the Tag: SemVerTag in i.e. SVN.

But which vX.Y.Z MSUT i use?

Is it a good idea to use: v2.2.118 or v2.2.0 ?

Cheers Roland

**Comment by mojombo** [comment]
Please note that the SemVerTag sub-specification is being removed from the specification very soon, so you are free to tag your versions any way you wish.

If you want to move to a SemVer compliant scheme, I would suggest your next release be 2.2.0.

**Comment by Ro42** [comment]
Dear Tom,

thank you for your quick response and for SEMVER.

Rgds Roland

2011/11/26 Tom Preston-Werner <
reply@reply.github.com
