### ISSUE TITLE
On http://semver.org/spec/v2.0.0-rc.1.html, it says "1.0.0-rc.1" instead of "2.0.0-rc.1".

### ISSUE THREAD

**Issue by dmitshur** [semver/semver.org#54]
This is just a duplicate of #55 but without code attached.

**Comment by dmitshur** [comment]
I couldn't find an easy way to attach code to an existing issue, so I figured it's easier to just close this empty one and make a new pull request.

**Comment by haacked** [comment]
That's fine. :)
