### ISSUE TITLE
Implementations section

### ISSUE THREAD

**Issue by zafarkhaja** [semver/semver.org#57]
The website lacks a section with implementations of the SemVer specification. It's obvious that a specification can't do much without implementations. I also believe that availability of [a wide range of] implementations is a sign of maturity for any protocol or specification.

There are already some good implementations in various languages being developed here on GitHub. So why don't we create a section with these implementations. We can gather all the implementations here in this issue and then create a PR. We might also want to select the most decent of them and not just pick everything that is posted.

Such section will definitely contribute to wider adoption of the SemVer specification.

**Comment by zafarkhaja** [comment]
I start with my own implementation written in Java https://github.com/zafarkhaja/java-semver. Feedback is welcome.

**Comment by colin-haber** [comment]
I've also written a Java implementation at https://github.com/dgn1nja/JemVer, although it's a bit more sparse than @zafarkhaja's is. I'll open a PR to add an implementations section if nobody else does when I have some more free time.

**Comment by tbull** [comment]
a small command line implementation that can be used for scripting and hooks
https://github.com/fsaintjacques/semver-tool
written in bash

**Comment by markchalloner** [comment]
A git plugin that can also validate correct version numbers in manifests, changelogs etc before tagging:

https://github.com/markchalloner/git-semver

**Comment by haacked** [comment]
A list of implementations is a great idea. Just need to figure out how we want to link to it from the main semver page.

**Comment by alexandrtovmach** [comment]
Added to plan here https://github.com/semver/semver/issues/573, closing in favor of main issue

**Comment by lorenzleutgeb** [comment]
I arrived here looking for a reference implementation or formal specification of SemVer. I don't see how this issue is represented in semver/semver#573, @alexandrtovmach could you please elaborate what you meant?
