### ISSUE TITLE
Disorganized Incremental Software Development (link)

### ISSUE THREAD

**Issue by pdorrell** [semver/semver.org#6]
You might be interested to read my article at http://www.1729.com/blog/DisorganizedIncrementalSoftwareDevelopment.html , which I wrote a while ago. It describes a more extreme solution to the problems of versioning and dependency management. Basically you use cryptographic hashes of interfaces and implementations as your version numbers. (A bit like Git does with source code.)

**Comment by chadwalters** [comment]
You might be interested in the Nix package management system described here: http://nixos.org/

**Comment by mojombo** [comment]
Awesome, thanks for the links!
