### ISSUE TITLE
A way to handle translations.

### ISSUE THREAD

**Issue by agustinf** [semver/semver.org#60]
I've translated 2.0.0-rc.2 to spanish.

I'd want to make a pull request to handle translations, but first please give me feedback on this proposal:
Folder "lang" on root would contain a set of folders "es", "it", etc. each of these would have an "index.md" and a "spec" folder with documents in the corresponding language. 
This way, http://semver.org/lang/es would show the spanish version.
on _layouts we could have default.html and spanish.html, italian.html, etc. which hold the links to the documents in the corresponding language.

What do you say? is there an easier, tidier way to do it?

**Comment by haacked** [comment]
I really like that idea.
