### ISSUE TITLE
Working in translation into Brazilian Portuguese pt-BR

### ISSUE THREAD

**Issue by rogeriopradoj** [semver/semver.org#65]
Hi @mojombo,

I'd like to inform you I'm working in translation of semver.org into Brazilian Portuguese (pt-BR), and, if possible, I'd like to have this issue assigned to me.

I've started this job on https://github.com/rogeriopradoj/translations/blob/master/translated/semantic-versioning/pt_BR.md, last year, and now that I realized you are allowing translations on official website site, I really excited with it.

I'll ask for @ArthurAssuncao to review the text after the pull request, he already help me with the later work.

Thanks in advance.

**Comment by haacked** [comment]
Thanks for your interest in providing a translation!

Please look at this commit to see what changes need to be made to support the translation: 8a9fb4a3274d0213f21ef8ea66ea173bc345ccbc

**Comment by rogeriopradoj** [comment]
Hi, @Haacked, thanks for the quick response!

**Comment by kelvinst** [comment]
@rogeriopradoj I think that @adilsoncarvalho just done this work in #74...

@Haacked can you take a look?

**Comment by rogeriopradoj** [comment]
Yeah, awesome.

I will work on revision so, ok?

See ya

**Comment by kelvinst** [comment]
Yep

I revised it too. But revision are never too much

Thanks \õ

**Comment by rogeriopradoj** [comment]
Closed, #96 is taking the last modifications.
