### ISSUE TITLE
Bloated CSS [unrelated to textual content]

### ISSUE THREAD

**Issue by mathiasbynens** [semver/semver.org#7]
Is there a reason why you’re including `blueprint.css` and `syntax.css`? You’re not using any of these at the moment.
If you do not plan on ever doing so, I would be happy to rewrite the CSS for you in 1 file (instead of 5) containing ± 20 lines (instead of, what, like 1000?). This would greatly reduce HTTP requests and file size, i.e. bandwidth.

Just let me know :)

Cheers

**Comment by mojombo** [comment]
The reason is that I copied the site from another that used that stuff. I'd welcome a patch that streamlined things!

**Comment by mathiasbynens** [comment]
[Fixed](http://github.com/mathiasbynens/semver.org/tree/7034d8ca94541fbee0a8968420c88e12ee9ad581).

This commit adds an unnecessary file, `css/.DS_Store` — sorry about that. I fixed this in [another commit](http://github.com/mathiasbynens/semver.org/commit/f967f6297c4674dc28916b87ea07ba330ce21a53).

**Comment by mojombo** [comment]
Thanks, this is now merged and deployed!

**Comment by mathiasbynens** [comment]
# Comparison

## Old files

### CSS

```
-rw-r--r--  1 Mathias  staff   1933 18 dec 09:37 css/blueprint/ie.css
-rw-r--r--  1 Mathias  staff   1284 18 dec 09:37 css/blueprint/print.css
-rw-r--r--  1 Mathias  staff  12058 18 dec 09:37 css/blueprint/screen.css
-rw-r--r--  1 Mathias  staff    668 18 dec 09:37 css/screen.css
-rw-r--r--  1 Mathias  staff   3738 18 dec 09:37 css/syntax.css
```

### HTML template

```
-rw-r--r--  1 Mathias  staff    818 18 dec 09:37 _layouts/default.html
```

### Total size

File size: 1933 + 1284 + 12058 + 668 + 3738 + 818 = _20499 bytes_
HTTP requests: 6

## New files

### CSS

```
-rw-r--r--  1 Mathias  staff   648 18 dec 09:37 css/main.css
```

### HTML template

```
-rw-r--r--  1 Mathias  staff   238 18 dec 09:37 _layouts/default.html
```

### Total size

File size: 648 + 238 = _886 bytes_
HTTP requests: 2

## Conclusion

The total size of the affected files was reduced from 20499 bytes to 886 bytes.
The number of HTTP requests was reduced from 6 to 2.
This optimization saves you from serving 19613 unneeded bytes and 4 HTTP requests every time semver.org is visited. Yay!

— [Mathias](http://mathiasbynens.be/)
