### ISSUE TITLE
What do you think about the minor odd is unstable, even is stable semantics added to versions?

### ISSUE THREAD

**Issue by ask** [semver/semver.org#8]
Is this conforming to semver, and if not, what is the reason?

**Comment by fguillen** [comment]
I like the possibility to mark this. +1 to add this kind of information on the semver standar.

**Comment by kristjan** [comment]
That feels like an overloading of the number. Use suffixes as defined in point (3): 1.0.4alpha.

**Comment by ask** [comment]
@kristjan That I wouldn't mind, if it wasn't for critical infrastructure like PyPI not supporting suffixes well

**Comment by serverhorror** [comment]
I think that would break semver. It would be necessary to create an additional rule. If you are on 2.X.X and introduce breaking changes that are stable, according to semver you should increment to at least 3.0.0 - according to your spec it would be at least 4.0.0 (hmmm where the the whole version 3 go then?)

Personally I think X.0.0 should never be considered stable (from a "user" point of view)

**Comment by mojombo** [comment]
I'm of the opinion that development should be done out of band of the traditional versioning number scheme. I'd suggest doing development on a separate dev branch and if other devs want to use those "versions", then they can install them directly from source. Once the dev branch is ready to hit primetime, then you can use the pre-release version part of SemVer to specify alpha, beta, and rc versions intended for public testing.
