### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by jprystowsky** [semver/semver.org#86]
Thanks for creating this! Just a note: It would be nice if the page at semver.org served over HTTPS.

Thanks.

(Moved by request from mojombo/semver#186)

**Comment by mwjames** [comment]
Would appreciated support for the `https` protocol as well because creating links to a non-https source in documentation material is somewhat difficult.

**Comment by doot0** [comment]
This could be done for free via Cloudflare.

https://www.cloudflare.com/ssl

**Comment by martinsuchan** [comment]
**Let's Encrypt CA** now offers free domain certificates for everyone and the setup + configuration is literally matter of minutes:
https://letsencrypt.org/getting-started/

**Comment by FichteFoll** [comment]
The site still does not properly support https.

The page is hosted using github pages and the CNAME feature. The server offers the certificate for *github.com (which also covers *.github.io), but that is obviously not valid for semver.org.
I don't know how this could be made possible, but supporting https in 2017 is a crutial issue that Github should investigate and provide solutions for, if there aren't any already.

Edit: Upstream issue: https://github.com/isaacs/github/issues/156. Seems like until this is done, it is only possible to use cloudflare.

**Comment by mschwager** [comment]
It's worth noting, Google favors HTTPS in its search results.

**Comment by davidjb** [comment]
Netlify (https://www.netlify.com/) also provides HTTPS via Let's Encrypt for open source static content for free.

**Comment by ExE-Boss** [comment]
This was reported to GitHub and a mirror was created at isaacs/github#156 (an unofficial tracker, originally for **isaacs**’s personal use, but is now used by many users to use to keep track of which requests they’ve sent to GitHub, and sometimes, some GitHub employees even actually check it every now and then).

**Comment by haacked** [comment]
Done!
