### ISSUE TITLE
Title of 2.0.0-rc.2 is incoherent

### ISSUE THREAD

**Issue by xmontero** [semver/semver.org#93]
For the page http://semver.org/spec/v2.0.0-rc.2.html the title reads 1.0.0-rc.2

I accidentally thought the issue place was the other repo (semver instead of semver.org), see history here:
https://github.com/mojombo/semver/issues/220

**Comment by xmontero** [comment]
Requested pull at #104

**Comment by haacked** [comment]
I merged #104. Pro tip, if you mention the issue you're fixing in a commit message like so "Fixes #104" then when the commit is merged, GitHub will automatically close the referenced issue.

**Comment by haacked** [comment]
Oh, thanks for logging the issue and the PR! :smile:
