### ISSUE TITLE
Move requests for feedback from mojombo/semver/issues to mojombo/semver.org/issues

### ISSUE THREAD

**Issue by rogeriopradoj** [semver/semver.org#99]
What are you think of moving all requests for feedback (in bottom of all pages) to https://github.com/mojombo/semver.org/issues (https://github.com/mojombo/semver/issues).

I can make the pull request if you are ok with it.

Thanks in advance.

**Comment by haacked** [comment]
Looks like this already happened at some point. Thanks for the issue and sorry for the late response.
